# Generated by Django 2.1.3 on 2018-11-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_contributor_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='professional_profil',
            new_name='professional_profile',
        ),
    ]
