# Generated by Django 2.1.3 on 2018-11-29 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181128_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.City', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='company',
            field=models.CharField(max_length=120, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='description',
            field=models.TextField(help_text='Ce que verront les autres membres en 1er sur ton profil', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Position', verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='professional_profile',
            field=models.CharField(help_text="Copie/colle ici l'URL de ton profil LinkedIn, Viadéo, ...", max_length=120, verbose_name='Lien professionel'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Sector', verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Skill', verbose_name='Une qualité'),
        ),
    ]
