# Generated by Django 2.1.3 on 2018-11-29 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181129_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Entreprise'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='description',
            field=models.TextField(blank=True, help_text='Ce que verront les autres membres en 1er sur ton profil', null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Position', verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='professional_profile',
            field=models.CharField(blank=True, help_text="Copie/colle ici l'URL de ton profil LinkedIn, Viadéo, ...", max_length=120, null=True, verbose_name='Lien professionel'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Sector', verbose_name='Secteur'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Skill', verbose_name='Une qualité'),
        ),
    ]
