# Generated by Django 2.1.3 on 2019-01-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181129_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'verbose_name': 'contributeur'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'poste'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'secteur'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'competence'},
        ),
        migrations.AlterField(
            model_name='contributor',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.City', verbose_name='Code Postal'),
        ),
    ]
