# Generated by Django 2.1.3 on 2019-01-08 01:05

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190107_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='Mots clefs'),
        ),
    ]
