# Generated by Django 2.1.3 on 2018-11-29 05:26

from django.db import migrations, models
import django.db.models.deletion
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181129_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.Nature', verbose_name='Nature du chantier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='users.Skill', verbose_name='Compétences recherchées'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255, verbose_name='projects.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titre du projet'),
        ),
    ]
