# Generated by Django 2.1.3 on 2018-11-29 06:17

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181129_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
