# Generated by Django 2.1.3 on 2019-01-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190107_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maturity',
            options={'verbose_name': 'maturité', 'verbose_name_plural': 'maturités'},
        ),
    ]
