# Generated by Django 2.1.3 on 2019-01-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20190107_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maturity',
            name='level',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
