# Generated by Django 2.1.3 on 2018-11-29 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20181128_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='users.Contributor'),
        ),
    ]
