# Generated by Django 2.1.3 on 2019-01-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20181129_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'verbose_name': 'idée'},
        ),
    ]
