# Generated by Django 2.1.3 on 2019-01-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercompany',
            options={'verbose_name_plural': 'entreprises membres'},
        ),
    ]
